CREATE OR REPLACE VIEW QUERY1 AS
SELECT P.FNAME, P.LNAME,COUNT(C.PATRON_ID) AS "NUMBER OF TIMES FAILED"
FROM PATRON P, CHECKS_OUT C
WHERE P.ID=C.PATRON_ID AND (C.ACT_RETURN_TIME>C.END_TIME OR (C.END_TIME<SYSDATE AND C.ACT_RETURN_TIME IS NULL)) AND C.END_TIME>='05-OCT-15' AND C.END_TIME<='05-NOV-15'
GROUP BY (P.FNAME, P.LNAME,C.PATRON_ID) ORDER BY P.FNAME DESC;

CREATE OR REPLACE VIEW QUERY2 AS
SELECT COUNT(*) AS "NO OF NULL RESERVATIONS"
FROM PATRON P, BOOKED B
WHERE P.ID=B.PATRON_ID AND B.CHECKED_OUT IS NULL AND B.CHECKED_IN IS NULL AND B.STATUS='INVALID' AND B.END_TIME>='30-OCT-15' AND B.END_TIME<='06-NOV-15';

CREATE OR REPLACE VIEW QUERY3 AS
SELECT SUM(t.TOTAL) as TOTAL_FINES
FROM
(SELECT SUM(AMOUNT) AS TOTAL
FROM FINES F, CHECKS_OUT C
WHERE F.CHECKS_OUT_ID=C.ID AND F.FINE_DATE>='05-OCT-15' AND F.FINE_DATE<='05-NOV-15'
UNION
SELECT SUM(AMOUNT) AS TOTAL
FROM CAM_FINES CF, BOOKED_CAMS BC
WHERE CF.BOOKED_CAM_ID=BC.ID AND BC.END_TIME>='05-OCT-15' AND BC.END_TIME<='05-NOV-15') t;

CREATE OR REPLACE VIEW QUERY4 AS
SELECT t.CAPACITY,t.NO_OF_REQUESTS
FROM (
SELECT R.CAPACITY, COUNT(*) AS "NO_OF_REQUESTS"
FROM BOOKED B, ROOMS R, PATRON P
WHERE R.ROOM_NUMBER=B.ROOM_NUMBER AND B.PATRON_ID=P.ID AND B.START_TIME>='05-OCT-15' AND B.START_TIME<='05-NOV-15'
GROUP BY CAPACITY ORDER BY NO_OF_REQUESTS DESC) t
WHERE ROWNUM <= 1;
