create or replace PROCEDURE CAMERA_RETURN(
  booking_id IN NUMBER,
  status OUT NUMBER
) 
IS
  cam_id NUMBER;
BEGIN
  SELECT CAM_ID INTO cam_id FROM BOOKED_CAMS WHERE ID = booking_id AND RETURNED_TIME IS NULL;
   UPDATE BOOKED_CAMS SET RETURNED_TIME = SYSDATE WHERE ID = booking_id;
  UPDATE CAMERAS SET STATUS = 0 WHERE ID = cam_id;
  status := 1;
  EXCEPTION
  WHEN NO_DATA_FOUND THEN
  status :=0;
END CAMERA_RETURN;