create or replace PROCEDURE CAMERA_CHECKED_OUT(
 -- List all the checked out camearas, so that user can select to return 
  patron_id IN NUMBER,
  c_result OUT SYS_REFCURSOR
)
IS
BEGIN
  OPEN c_result FOR
  SELECT BOOKED_CAMS.ID, CAMERAS.MAKE,CAMERAS.MODEL,CAMERAS.CONFIG,CAMERAS.LID,CAMERAS.MEMORY FROM CAMERAS, BOOKED_CAMS 
  WHERE BOOKED_CAMS.PATRON_ID = patron_id AND BOOKED_CAMS.CAM_ID = CAMERAS.ID AND BOOKED_CAMS.RETURNED_TIME IS NULL;
END CAMERA_CHECKED_OUT;