

CREATE VIEW QUERY1 AS
SELECT P.FNAME, P.LNAME,COUNT(C.PATRON_ID) AS "NUMBER OF TIMES FAILED"
FROM PATRON P, CHECKS_OUT C
WHERE P.ID=C.PATRON_ID AND (C.RETURNED_TIME>C.END_TIME OR (C.END_TIME<SYSDATE AND C.RETURNED_TIME IS NULL)) AND C.END_TIME>='05-OCT-15' AND C.END_TIME<='05-NOV-15' 
GROUP BY (P.FNAME, P.LNAME,C.PATRON_ID);

CREATE VIEW QUERY3 AS
SELECT SUM(t.COPIES_SUM)
FROM 
(SELECT SUM(AMOUNT) AS COPIES_SUM
FROM FINES F, CHECKS_OUT C
WHERE F.CHECKS_OUT_ID=C.ID AND F.FINE_DATE>='05-OCT-15' AND F.FINE_DATE<='05-NOV-15'
UNION 
SELECT SUM(AMOUNT) AS CAMERA_SUM
FROM CAM_FINES CF, BOOKED_CAMS BC
WHERE CF.BOOKED_CAM_ID=BC.ID AND CF.FINE_DATE>='05-OCT-15' AND CF.FINE_DATE<='05-NOV-15') t

CREATE VIEW QUERY4 AS
SELECT t.CAPACITY,t.NO_OF_REQUESTS
FROM (
SELECT R.CAPACITY, COUNT(*) AS "NO_OF_REQUESTS"
FROM BOOKED B, ROOMS R, PATRON P
WHERE R.ROOM_NUMBER=B.ROOM_NUMBER AND B.PATRON_ID=P.ID AND B.START_TIME>='05-OCT-15' AND B.START_TIME<='05-NOV-15'
GROUP BY CAPACITY) t
WHERE ROWNUM <= 1
ORDER BY t.NO_OF_REQUESTS DESC;


