INSERT INTO Departments (abbreviation, name) VALUES("AA","Advanced Analytics");
INSERT INTO Departments (abbreviation, name) VALUES("ACC","Accounting");
INSERT INTO Departments (abbreviation, name) VALUES("ADN","Art and Design");
INSERT INTO Departments (abbreviation, name) VALUES("AEC","Applied Ecology");
INSERT INTO Departments (abbreviation, name) VALUES("AEE","Agricultural and Extension Education");
INSERT INTO Departments (abbreviation, name) VALUES("AES","Agricultural and Environmental Systems");
INSERT INTO Departments (abbreviation, name) VALUES("AFS","Africana Studies");
INSERT INTO Departments (abbreviation, name) VALUES("AGI","Agricultural Institute");
INSERT INTO Departments (abbreviation, name) VALUES("ALS","Agriculture and Life Sciences");
INSERT INTO Departments (abbreviation, name) VALUES("ANS","Animal Science");
INSERT INTO Departments (abbreviation, name) VALUES("ANT","Anthropology");
INSERT INTO Departments (abbreviation, name) VALUES("ARC","Architecture");
INSERT INTO Departments (abbreviation, name) VALUES("ARE","Agricultural and Resource Economics");
INSERT INTO Departments (abbreviation, name) VALUES("ARS","Arts Studies");
INSERT INTO Departments (abbreviation, name) VALUES("AS","Aerospace Studies");
INSERT INTO Departments (abbreviation, name) VALUES("AVS","Arts Village");
INSERT INTO Departments (abbreviation, name) VALUES("BAE","Biological and Agricultural Engineering");
INSERT INTO Departments (abbreviation, name) VALUES("BBS","Bioprocessing");
INSERT INTO Departments (abbreviation, name) VALUES("BCH","Biochemistry");
INSERT INTO Departments (abbreviation, name) VALUES("BEC","Biomanufacturing Training Education Center");
INSERT INTO Departments (abbreviation, name) VALUES("BIO","Biological Sciences");
INSERT INTO Departments (abbreviation, name) VALUES("BIT","Biotechnology");
INSERT INTO Departments (abbreviation, name) VALUES("BMA","Biomathematics");
INSERT INTO Departments (abbreviation, name) VALUES("BME","Biomedical Engineering");
INSERT INTO Departments (abbreviation, name) VALUES("BUS","Business Management");
INSERT INTO Departments (abbreviation, name) VALUES("CBS","Comparative Biological Science");
INSERT INTO Departments (abbreviation, name) VALUES("CE","Civil Engineering");
INSERT INTO Departments (abbreviation, name) VALUES("CH","Chemistry");
INSERT INTO Departments (abbreviation, name) VALUES("CHE","Chemical Engineering");
INSERT INTO Departments (abbreviation, name) VALUES("CLA","Foreign Language");
INSERT INTO Departments (abbreviation, name) VALUES("CNR","College of Natural Resources");
INSERT INTO Departments (abbreviation, name) VALUES("COM","Communication");
INSERT INTO Departments (abbreviation, name) VALUES("COP","Cooperative Education");
INSERT INTO Departments (abbreviation, name) VALUES("CRD","Communication Rhetoric & Digital Media");
INSERT INTO Departments (abbreviation, name) VALUES("CS","Crop Science");
INSERT INTO Departments (abbreviation, name) VALUES("CSC","Computer Science");
INSERT INTO Departments (abbreviation, name) VALUES("D","Design");
INSERT INTO Departments (abbreviation, name) VALUES("DAN","Dance");
INSERT INTO Departments (abbreviation, name) VALUES("DDN","Design courses for Graduate Students");
INSERT INTO Departments (abbreviation, name) VALUES("DS","Design Studies");
INSERT INTO Departments (abbreviation, name) VALUES("E","Engineering");
INSERT INTO Departments (abbreviation, name) VALUES("EA","Environmental Assessment");
INSERT INTO Departments (abbreviation, name) VALUES("EAC","Adult & Higher Education");
INSERT INTO Departments (abbreviation, name) VALUES("EC","Economics");
INSERT INTO Departments (abbreviation, name) VALUES("ECD","Counselor Education");
INSERT INTO Departments (abbreviation, name) VALUES("ECE","Electrical and Computer Engineering");
INSERT INTO Departments (abbreviation, name) VALUES("ECG","Graduate Economics");
INSERT INTO Departments (abbreviation, name) VALUES("ECI","Curriculum and Instruction");
INSERT INTO Departments (abbreviation, name) VALUES("ECO","Ecology");
INSERT INTO Departments (abbreviation, name) VALUES("ED","Education");
INSERT INTO Departments (abbreviation, name) VALUES("EDP","Educational Psychology");
INSERT INTO Departments (abbreviation, name) VALUES("EGR","EGR");
INSERT INTO Departments (abbreviation, name) VALUES("EI","Entrepreneurship Initiative");
INSERT INTO Departments (abbreviation, name) VALUES("ELM","Elementary Education");
INSERT INTO Departments (abbreviation, name) VALUES("ELP","Educ Leadership & Program Eval");
INSERT INTO Departments (abbreviation, name) VALUES("EMA","Entrepreneurship in Music and the Arts");
INSERT INTO Departments (abbreviation, name) VALUES("EMS","Math & Science Education");
INSERT INTO Departments (abbreviation, name) VALUES("ENG","English");
INSERT INTO Departments (abbreviation, name) VALUES("ENT","Entomology");
INSERT INTO Departments (abbreviation, name) VALUES("ES","Environmental Science");
INSERT INTO Departments (abbreviation, name) VALUES("ET","Environmental Technology");
INSERT INTO Departments (abbreviation, name) VALUES("FB","Forest Biomaterials");
INSERT INTO Departments (abbreviation, name) VALUES("FIM","Financial Mathematics");
INSERT INTO Departments (abbreviation, name) VALUES("FL","Foreign Languages");
INSERT INTO Departments (abbreviation, name) VALUES("FLA","Foreign Languages and Literatures");
INSERT INTO Departments (abbreviation, name) VALUES("FLC","Foreign Language");
INSERT INTO Departments (abbreviation, name) VALUES("FLE","Foreign Language");
INSERT INTO Departments (abbreviation, name) VALUES("FLF","Foreign Language");
INSERT INTO Departments (abbreviation, name) VALUES("FLG","Foreign Language");
INSERT INTO Departments (abbreviation, name) VALUES("FLI","Foreign Language");
INSERT INTO Departments (abbreviation, name) VALUES("FLJ","Foreign Language");
INSERT INTO Departments (abbreviation, name) VALUES("FLN","Foreign Language");
INSERT INTO Departments (abbreviation, name) VALUES("FLP","Foreign Language");
INSERT INTO Departments (abbreviation, name) VALUES("FLR","Foreign Language");
INSERT INTO Departments (abbreviation, name) VALUES("FLS","Foreign Language");
INSERT INTO Departments (abbreviation, name) VALUES("FM","Feed Mill");
INSERT INTO Departments (abbreviation, name) VALUES("FOR","Forestry");
INSERT INTO Departments (abbreviation, name) VALUES("FPS","Fiber and Polymer Science");
INSERT INTO Departments (abbreviation, name) VALUES("FS","Food Science");
INSERT INTO Departments (abbreviation, name) VALUES("FSA","Food Science");
INSERT INTO Departments (abbreviation, name) VALUES("FTD","Fashion and Textile Design");
INSERT INTO Departments (abbreviation, name) VALUES("FTM","Fashion and Textile Management");
INSERT INTO Departments (abbreviation, name) VALUES("FW","Fisheries & Wildlife Sciences");
INSERT INTO Departments (abbreviation, name) VALUES("GC","Graphic Communications");
INSERT INTO Departments (abbreviation, name) VALUES("GD","Graphic Design");
INSERT INTO Departments (abbreviation, name) VALUES("GES","Genetic Engineering and Society");
INSERT INTO Departments (abbreviation, name) VALUES("GIS","Geographic Information Systems");
INSERT INTO Departments (abbreviation, name) VALUES("GN","Genetics");
INSERT INTO Departments (abbreviation, name) VALUES("GR","Graduate Special Categories");
INSERT INTO Departments (abbreviation, name) VALUES("GRK","Foreign Language");
INSERT INTO Departments (abbreviation, name) VALUES("GTI","NC Global Training Initiative");
INSERT INTO Departments (abbreviation, name) VALUES("HA","History of Art");
INSERT INTO Departments (abbreviation, name) VALUES("HESA","HESA");
INSERT INTO Departments (abbreviation, name) VALUES("HESD","Health Exercise Studies Dance");
INSERT INTO Departments (abbreviation, name) VALUES("HESE","Health Exercise Studies Emergency Medicine");
INSERT INTO Departments (abbreviation, name) VALUES("HESF","Health Exercise Studies Fitness");
INSERT INTO Departments (abbreviation, name) VALUES("HESM","Health and Exercise Studies Minor");
INSERT INTO Departments (abbreviation, name) VALUES("HESO","Health Exercise Studies Outdoor");
INSERT INTO Departments (abbreviation, name) VALUES("HESR","Health Exercise Studies Racquet");
INSERT INTO Departments (abbreviation, name) VALUES("HESS","Health Exercise Studies Specialty");
INSERT INTO Departments (abbreviation, name) VALUES("HEST","Health Exercise Studies Team");
INSERT INTO Departments (abbreviation, name) VALUES("HI","History");
INSERT INTO Departments (abbreviation, name) VALUES("HON","Honors");
INSERT INTO Departments (abbreviation, name) VALUES("HS","Horticulture Science");
INSERT INTO Departments (abbreviation, name) VALUES("ID","Industrial Design");
INSERT INTO Departments (abbreviation, name) VALUES("IDS","Interdisciplinary Studies");
INSERT INTO Departments (abbreviation, name) VALUES("IMM","Immunology");
INSERT INTO Departments (abbreviation, name) VALUES("IMS","Integrated Manufacturing Sys");
INSERT INTO Departments (abbreviation, name) VALUES("IPGE","Interdisciplinary Perspectives");
INSERT INTO Departments (abbreviation, name) VALUES("IPUS","Interdisciplinary Perspectives and U.S. Diversity");
INSERT INTO Departments (abbreviation, name) VALUES("IS","International Studies");
INSERT INTO Departments (abbreviation, name) VALUES("ISE","Industrial and Systems Engineering");
INSERT INTO Departments (abbreviation, name) VALUES("JDP","Joint Degree Program placeholder courses");
INSERT INTO Departments (abbreviation, name) VALUES("LAR","Landscape Architecture");
INSERT INTO Departments (abbreviation, name) VALUES("LAT","Foreign Language");
INSERT INTO Departments (abbreviation, name) VALUES("LOG","Logic");
INSERT INTO Departments (abbreviation, name) VALUES("LPS","Leadership in the Public Sector");
INSERT INTO Departments (abbreviation, name) VALUES("LSC","Life Sciences First Year");
INSERT INTO Departments (abbreviation, name) VALUES("M","Management");
INSERT INTO Departments (abbreviation, name) VALUES("MA","Mathematics");
INSERT INTO Departments (abbreviation, name) VALUES("MAA","Math in Agriculture and Related Sciences");
INSERT INTO Departments (abbreviation, name) VALUES("MAE","Mechanical & Aerospace Engr");
INSERT INTO Departments (abbreviation, name) VALUES("MB","Microbiology");
INSERT INTO Departments (abbreviation, name) VALUES("MBA","Business Administration");
INSERT INTO Departments (abbreviation, name) VALUES("MDS","Multidisciplinary Studies");
INSERT INTO Departments (abbreviation, name) VALUES("MEA","Marine, Earth, and Atmospheric Sciences");
INSERT INTO Departments (abbreviation, name) VALUES("MIE","Management Innovation Entrepreneurship");
INSERT INTO Departments (abbreviation, name) VALUES("MIS","International Studies");
INSERT INTO Departments (abbreviation, name) VALUES("MLS","Liberal Studies");
INSERT INTO Departments (abbreviation, name) VALUES("MS","Military Science");
INSERT INTO Departments (abbreviation, name) VALUES("MSE","Materials Science and Engineering");
INSERT INTO Departments (abbreviation, name) VALUES("MT","Medical Textiles");
INSERT INTO Departments (abbreviation, name) VALUES("MUS","Music");
INSERT INTO Departments (abbreviation, name) VALUES("NE","Nuclear Engineering");
INSERT INTO Departments (abbreviation, name) VALUES("NPS","Nonprofit Studies");
INSERT INTO Departments (abbreviation, name) VALUES("NR","Natural Resources");
INSERT INTO Departments (abbreviation, name) VALUES("NS","Naval Science");
INSERT INTO Departments (abbreviation, name) VALUES("NSGK","Natural Sciences and Global Knowledge");
INSERT INTO Departments (abbreviation, name) VALUES("NTR","Nutrition");
INSERT INTO Departments (abbreviation, name) VALUES("NW","Nonwovens");
INSERT INTO Departments (abbreviation, name) VALUES("OR","Operations Research");
INSERT INTO Departments (abbreviation, name) VALUES("PA","Public Administration");
INSERT INTO Departments (abbreviation, name) VALUES("PB","Plant Biology");
INSERT INTO Departments (abbreviation, name) VALUES("PCC","Polymer and Color Chemistry");
INSERT INTO Departments (abbreviation, name) VALUES("PER","Foreign Language");
INSERT INTO Departments (abbreviation, name) VALUES("PHI","Philosophy");
INSERT INTO Departments (abbreviation, name) VALUES("PHY","Physiology");
INSERT INTO Departments (abbreviation, name) VALUES("PO","Poultry Science");
INSERT INTO Departments (abbreviation, name) VALUES("PP","Plant Pathology");
INSERT INTO Departments (abbreviation, name) VALUES("PRK","Park Scholars");
INSERT INTO Departments (abbreviation, name) VALUES("PRT","Parks, Recreation, and Tourism Management");
INSERT INTO Departments (abbreviation, name) VALUES("PS","Political Science");
INSERT INTO Departments (abbreviation, name) VALUES("PSE","Paper Science Engineering");
INSERT INTO Departments (abbreviation, name) VALUES("PSY","Psychology");
INSERT INTO Departments (abbreviation, name) VALUES("PY","Physics");
INSERT INTO Departments (abbreviation, name) VALUES("REL","Religious Studies");
INSERT INTO Departments (abbreviation, name) VALUES("SLC","Shelton Leadership Course");
INSERT INTO Departments (abbreviation, name) VALUES("SMT","Sustainable Materials and Technology");
INSERT INTO Departments (abbreviation, name) VALUES("SOC","Sociology");
INSERT INTO Departments (abbreviation, name) VALUES("SSC","Soil Science");
INSERT INTO Departments (abbreviation, name) VALUES("ST","Statistics");
INSERT INTO Departments (abbreviation, name) VALUES("STS","Science, Technology and Society");
INSERT INTO Departments (abbreviation, name) VALUES("SVM","Specialized Veterinary Medicine");
INSERT INTO Departments (abbreviation, name) VALUES("SW","Social Work");
INSERT INTO Departments (abbreviation, name) VALUES("T","Textiles");
INSERT INTO Departments (abbreviation, name) VALUES("TC","Textile Chemistry");
INSERT INTO Departments (abbreviation, name) VALUES("TDE","Technology Engineering and Design Education");
INSERT INTO Departments (abbreviation, name) VALUES("TE","Textile Engineering");
INSERT INTO Departments (abbreviation, name) VALUES("TED","Technology Education");
INSERT INTO Departments (abbreviation, name) VALUES("THE","Theatre");
INSERT INTO Departments (abbreviation, name) VALUES("TMS","Textile Materials Science");
INSERT INTO Departments (abbreviation, name) VALUES("TOX","Toxicology");
INSERT INTO Departments (abbreviation, name) VALUES("TT","Textile Technology");
INSERT INTO Departments (abbreviation, name) VALUES("TTM","Textile Technology Management");
INSERT INTO Departments (abbreviation, name) VALUES("USC","University Studies Course");
INSERT INTO Departments (abbreviation, name) VALUES("USP","University Scholars Program");
INSERT INTO Departments (abbreviation, name) VALUES("VMB","Veterinary Science");
INSERT INTO Departments (abbreviation, name) VALUES("VMC","Veterinary Medicine");
INSERT INTO Departments (abbreviation, name) VALUES("VMP","Veterinary Science");
INSERT INTO Departments (abbreviation, name) VALUES("WGS","Women's and Gender Studies");
INSERT INTO Departments (abbreviation, name) VALUES("WPS","Wood and Paper Science");
INSERT INTO Departments (abbreviation, name) VALUES("WRT","Professional Writing");
INSERT INTO Departments (abbreviation, name) VALUES("YFCS","Youth, Family, and Community Science");
INSERT INTO Departments (abbreviation, name) VALUES("ZO","Zoology");
