INSERT INTO Departments (abbreviation, name) VALUES('AA','Advanced Analytics');
INSERT INTO Departments (abbreviation, name) VALUES('ACC','Accounting');
INSERT INTO Departments (abbreviation, name) VALUES('ADN','Art and Design');
INSERT INTO Departments (abbreviation, name) VALUES('AEC','Applied Ecology');
INSERT INTO Departments (abbreviation, name) VALUES('AEE','Agricultural and Extension Education');
INSERT INTO Departments (abbreviation, name) VALUES('AES','Agricultural and Environmental Systems');
INSERT INTO Departments (abbreviation, name) VALUES('AFS','Africana Studies');
INSERT INTO Departments (abbreviation, name) VALUES('AGI','Agricultural Institute');
INSERT INTO Departments (abbreviation, name) VALUES('ALS','Agriculture and Life Sciences');
INSERT INTO Departments (abbreviation, name) VALUES('ANS','Animal Science');
INSERT INTO Departments (abbreviation, name) VALUES('ANT','Anthropology');
INSERT INTO Departments (abbreviation, name) VALUES('ARC','Architecture');
INSERT INTO Departments (abbreviation, name) VALUES('ARE','Agricultural and Resource Economics');
INSERT INTO Departments (abbreviation, name) VALUES('ARS','Arts Studies');
INSERT INTO Departments (abbreviation, name) VALUES('AS','Aerospace Studies');
INSERT INTO Departments (abbreviation, name) VALUES('AVS','Arts Village');
INSERT INTO Departments (abbreviation, name) VALUES('BAE','Biological and Agricultural Engineering');
INSERT INTO Departments (abbreviation, name) VALUES('BBS','Bioprocessing');
INSERT INTO Departments (abbreviation, name) VALUES('BCH','Biochemistry');
INSERT INTO Departments (abbreviation, name) VALUES('BEC','Biomanufacturing Training Education Center');
INSERT INTO Departments (abbreviation, name) VALUES('BIO','Biological Sciences');
INSERT INTO Departments (abbreviation, name) VALUES('BIT','Biotechnology');
INSERT INTO Departments (abbreviation, name) VALUES('BMA','Biomathematics');
INSERT INTO Departments (abbreviation, name) VALUES('BME','Biomedical Engineering');
INSERT INTO Departments (abbreviation, name) VALUES('BUS','Business Management');
INSERT INTO Departments (abbreviation, name) VALUES('CBS','Comparative Biological Science');
INSERT INTO Departments (abbreviation, name) VALUES('CE','Civil Engineering');
INSERT INTO Departments (abbreviation, name) VALUES('CH','Chemistry');
INSERT INTO Departments (abbreviation, name) VALUES('CHE','Chemical Engineering');
INSERT INTO Departments (abbreviation, name) VALUES('CLA','Foreign Language');
INSERT INTO Departments (abbreviation, name) VALUES('CNR','College of Natural Resources');
INSERT INTO Departments (abbreviation, name) VALUES('COM','Communication');
INSERT INTO Departments (abbreviation, name) VALUES('COP','Cooperative Education');
INSERT INTO Departments (abbreviation, name) VALUES('CRD','Communication Rhetoric and Digital Media');
INSERT INTO Departments (abbreviation, name) VALUES('CS','Crop Science');
INSERT INTO Departments (abbreviation, name) VALUES('CSC','Computer Science');
INSERT INTO Departments (abbreviation, name) VALUES('D','Design');
INSERT INTO Departments (abbreviation, name) VALUES('DAN','Dance');
INSERT INTO Departments (abbreviation, name) VALUES('DDN','Design courses for Graduate Students');
INSERT INTO Departments (abbreviation, name) VALUES('DS','Design Studies');
INSERT INTO Departments (abbreviation, name) VALUES('E','Engineering');
INSERT INTO Departments (abbreviation, name) VALUES('EA','Environmental Assessment');
INSERT INTO Departments (abbreviation, name) VALUES('EAC','Adult and Higher Education');
INSERT INTO Departments (abbreviation, name) VALUES('EC','Economics');
INSERT INTO Departments (abbreviation, name) VALUES('ECD','Counselor Education');
INSERT INTO Departments (abbreviation, name) VALUES('ECE','Electrical and Computer Engineering');
INSERT INTO Departments (abbreviation, name) VALUES('ECG','Graduate Economics');
INSERT INTO Departments (abbreviation, name) VALUES('ECI','Curriculum and Instruction');
INSERT INTO Departments (abbreviation, name) VALUES('ECO','Ecology');
INSERT INTO Departments (abbreviation, name) VALUES('ED','Education');
INSERT INTO Departments (abbreviation, name) VALUES('EDP','Educational Psychology');
INSERT INTO Departments (abbreviation, name) VALUES('EGR','EGR');
INSERT INTO Departments (abbreviation, name) VALUES('EI','Entrepreneurship Initiative');
INSERT INTO Departments (abbreviation, name) VALUES('ELM','Elementary Education');
INSERT INTO Departments (abbreviation, name) VALUES('ELP','Educ Leadership and Program Eval');
INSERT INTO Departments (abbreviation, name) VALUES('EMA','Entrepreneurship in Music and the Arts');
INSERT INTO Departments (abbreviation, name) VALUES('EMS','Math and Science Education');
INSERT INTO Departments (abbreviation, name) VALUES('ENG','English');
INSERT INTO Departments (abbreviation, name) VALUES('ENT','Entomology');
INSERT INTO Departments (abbreviation, name) VALUES('ES','Environmental Science');
INSERT INTO Departments (abbreviation, name) VALUES('ET','Environmental Technology');
INSERT INTO Departments (abbreviation, name) VALUES('FB','Forest Biomaterials');
INSERT INTO Departments (abbreviation, name) VALUES('FIM','Financial Mathematics');
INSERT INTO Departments (abbreviation, name) VALUES('FL','Foreign Languages');
INSERT INTO Departments (abbreviation, name) VALUES('FLA','Foreign Languages and Literatures');
INSERT INTO Departments (abbreviation, name) VALUES('FLC','Foreign Language');
INSERT INTO Departments (abbreviation, name) VALUES('FLE','Foreign Language');
INSERT INTO Departments (abbreviation, name) VALUES('FLF','Foreign Language');
INSERT INTO Departments (abbreviation, name) VALUES('FLG','Foreign Language');
INSERT INTO Departments (abbreviation, name) VALUES('FLI','Foreign Language');
INSERT INTO Departments (abbreviation, name) VALUES('FLJ','Foreign Language');
INSERT INTO Departments (abbreviation, name) VALUES('FLN','Foreign Language');
INSERT INTO Departments (abbreviation, name) VALUES('FLP','Foreign Language');
INSERT INTO Departments (abbreviation, name) VALUES('FLR','Foreign Language');
INSERT INTO Departments (abbreviation, name) VALUES('FLS','Foreign Language');
INSERT INTO Departments (abbreviation, name) VALUES('FM','Feed Mill');
INSERT INTO Departments (abbreviation, name) VALUES('FOR','Forestry');
INSERT INTO Departments (abbreviation, name) VALUES('FPS','Fiber and Polymer Science');
INSERT INTO Departments (abbreviation, name) VALUES('FS','Food Science');
INSERT INTO Departments (abbreviation, name) VALUES('FSA','Food Science');
INSERT INTO Departments (abbreviation, name) VALUES('FTD','Fashion and Textile Design');
INSERT INTO Departments (abbreviation, name) VALUES('FTM','Fashion and Textile Management');
INSERT INTO Departments (abbreviation, name) VALUES('FW','Fisheries and Wildlife Sciences');
INSERT INTO Departments (abbreviation, name) VALUES('GC','Graphic Communications');
INSERT INTO Departments (abbreviation, name) VALUES('GD','Graphic Design');
INSERT INTO Departments (abbreviation, name) VALUES('GES','Genetic Engineering and Society');
INSERT INTO Departments (abbreviation, name) VALUES('GIS','Geographic Information Systems');
INSERT INTO Departments (abbreviation, name) VALUES('GN','Genetics');
INSERT INTO Departments (abbreviation, name) VALUES('GR','Graduate Special Categories');
INSERT INTO Departments (abbreviation, name) VALUES('GRK','Foreign Language');
INSERT INTO Departments (abbreviation, name) VALUES('GTI','NC Global Training Initiative');
INSERT INTO Departments (abbreviation, name) VALUES('HA','History of Art');
INSERT INTO Departments (abbreviation, name) VALUES('HESA','HESA');
INSERT INTO Departments (abbreviation, name) VALUES('HESD','Health Exercise Studies Dance');
INSERT INTO Departments (abbreviation, name) VALUES('HESE','Health Exercise Studies Emergency Medicine');
INSERT INTO Departments (abbreviation, name) VALUES('HESF','Health Exercise Studies Fitness');
INSERT INTO Departments (abbreviation, name) VALUES('HESM','Health and Exercise Studies Minor');
INSERT INTO Departments (abbreviation, name) VALUES('HESO','Health Exercise Studies Outdoor');
INSERT INTO Departments (abbreviation, name) VALUES('HESR','Health Exercise Studies Racquet');
INSERT INTO Departments (abbreviation, name) VALUES('HESS','Health Exercise Studies Specialty');
INSERT INTO Departments (abbreviation, name) VALUES('HEST','Health Exercise Studies Team');
INSERT INTO Departments (abbreviation, name) VALUES('HI','History');
INSERT INTO Departments (abbreviation, name) VALUES('HON','Honors');
INSERT INTO Departments (abbreviation, name) VALUES('HS','Horticulture Science');
INSERT INTO Departments (abbreviation, name) VALUES('ID','Industrial Design');
INSERT INTO Departments (abbreviation, name) VALUES('IDS','Interdisciplinary Studies');
INSERT INTO Departments (abbreviation, name) VALUES('IMM','Immunology');
INSERT INTO Departments (abbreviation, name) VALUES('IMS','Integrated Manufacturing Sys');
INSERT INTO Departments (abbreviation, name) VALUES('IPGE','Interdisciplinary Perspectives');
INSERT INTO Departments (abbreviation, name) VALUES('IPUS','Interdisciplinary Perspectives and U.S. Diversity');
INSERT INTO Departments (abbreviation, name) VALUES('IS','International Studies');
INSERT INTO Departments (abbreviation, name) VALUES('ISE','Industrial and Systems Engineering');
INSERT INTO Departments (abbreviation, name) VALUES('JDP','Joint Degree Program placeholder courses');
INSERT INTO Departments (abbreviation, name) VALUES('LAR','Landscape Architecture');
INSERT INTO Departments (abbreviation, name) VALUES('LAT','Foreign Language');
INSERT INTO Departments (abbreviation, name) VALUES('LOG','Logic');
INSERT INTO Departments (abbreviation, name) VALUES('LPS','Leadership in the Public Sector');
INSERT INTO Departments (abbreviation, name) VALUES('LSC','Life Sciences First Year');
INSERT INTO Departments (abbreviation, name) VALUES('M','Management');
INSERT INTO Departments (abbreviation, name) VALUES('MA','Mathematics');
INSERT INTO Departments (abbreviation, name) VALUES('MAA','Math in Agriculture and Related Sciences');
INSERT INTO Departments (abbreviation, name) VALUES('MAE','Mechanical and Aerospace Engr');
INSERT INTO Departments (abbreviation, name) VALUES('MB','Microbiology');
INSERT INTO Departments (abbreviation, name) VALUES('MBA','Business Administration');
INSERT INTO Departments (abbreviation, name) VALUES('MDS','Multidisciplinary Studies');
INSERT INTO Departments (abbreviation, name) VALUES('MEA','Marine, Earth, and Atmospheric Sciences');
INSERT INTO Departments (abbreviation, name) VALUES('MIE','Management Innovation Entrepreneurship');
INSERT INTO Departments (abbreviation, name) VALUES('MIS','International Studies');
INSERT INTO Departments (abbreviation, name) VALUES('MLS','Liberal Studies');
INSERT INTO Departments (abbreviation, name) VALUES('MS','Military Science');
INSERT INTO Departments (abbreviation, name) VALUES('MSE','Materials Science and Engineering');
INSERT INTO Departments (abbreviation, name) VALUES('MT','Medical Textiles');
INSERT INTO Departments (abbreviation, name) VALUES('MUS','Music');
INSERT INTO Departments (abbreviation, name) VALUES('NE','Nuclear Engineering');
INSERT INTO Departments (abbreviation, name) VALUES('NPS','Nonprofit Studies');
INSERT INTO Departments (abbreviation, name) VALUES('NR','Natural Resources');
INSERT INTO Departments (abbreviation, name) VALUES('NS','Naval Science');
INSERT INTO Departments (abbreviation, name) VALUES('NSGK','Natural Sciences and Global Knowledge');
INSERT INTO Departments (abbreviation, name) VALUES('NTR','Nutrition');
INSERT INTO Departments (abbreviation, name) VALUES('NW','Nonwovens');
INSERT INTO Departments (abbreviation, name) VALUES('OR','Operations Research');
INSERT INTO Departments (abbreviation, name) VALUES('PA','Public Administration');
INSERT INTO Departments (abbreviation, name) VALUES('PB','Plant Biology');
INSERT INTO Departments (abbreviation, name) VALUES('PCC','Polymer and Color Chemistry');
INSERT INTO Departments (abbreviation, name) VALUES('PER','Foreign Language');
INSERT INTO Departments (abbreviation, name) VALUES('PHI','Philosophy');
INSERT INTO Departments (abbreviation, name) VALUES('PHY','Physiology');
INSERT INTO Departments (abbreviation, name) VALUES('PO','Poultry Science');
INSERT INTO Departments (abbreviation, name) VALUES('PP','Plant Pathology');
INSERT INTO Departments (abbreviation, name) VALUES('PRK','Park Scholars');
INSERT INTO Departments (abbreviation, name) VALUES('PRT','Parks, Recreation, and Tourism Management');
INSERT INTO Departments (abbreviation, name) VALUES('PS','Political Science');
INSERT INTO Departments (abbreviation, name) VALUES('PSE','Paper Science Engineering');
INSERT INTO Departments (abbreviation, name) VALUES('PSY','Psychology');
INSERT INTO Departments (abbreviation, name) VALUES('PY','Physics');
INSERT INTO Departments (abbreviation, name) VALUES('REL','Religious Studies');
INSERT INTO Departments (abbreviation, name) VALUES('SLC','Shelton Leadership Course');
INSERT INTO Departments (abbreviation, name) VALUES('SMT','Sustainable Materials and Technology');
INSERT INTO Departments (abbreviation, name) VALUES('SOC','Sociology');
INSERT INTO Departments (abbreviation, name) VALUES('SSC','Soil Science');
INSERT INTO Departments (abbreviation, name) VALUES('ST','Statistics');
INSERT INTO Departments (abbreviation, name) VALUES('STS','Science, Technology and Society');
INSERT INTO Departments (abbreviation, name) VALUES('SVM','Specialized Veterinary Medicine');
INSERT INTO Departments (abbreviation, name) VALUES('SW','Social Work');
INSERT INTO Departments (abbreviation, name) VALUES('T','Textiles');
INSERT INTO Departments (abbreviation, name) VALUES('TC','Textile Chemistry');
INSERT INTO Departments (abbreviation, name) VALUES('TDE','Technology Engineering and Design Education');
INSERT INTO Departments (abbreviation, name) VALUES('TE','Textile Engineering');
INSERT INTO Departments (abbreviation, name) VALUES('TED','Technology Education');
INSERT INTO Departments (abbreviation, name) VALUES('THE','Theatre');
INSERT INTO Departments (abbreviation, name) VALUES('TMS','Textile Materials Science');
INSERT INTO Departments (abbreviation, name) VALUES('TOX','Toxicology');
INSERT INTO Departments (abbreviation, name) VALUES('TT','Textile Technology');
INSERT INTO Departments (abbreviation, name) VALUES('TTM','Textile Technology Management');
INSERT INTO Departments (abbreviation, name) VALUES('USC','University Studies Course');
INSERT INTO Departments (abbreviation, name) VALUES('USP','University Scholars Program');
INSERT INTO Departments (abbreviation, name) VALUES('VMB','Veterinary Science');
INSERT INTO Departments (abbreviation, name) VALUES('VMC','Veterinary Medicine');
INSERT INTO Departments (abbreviation, name) VALUES('VMP','Veterinary Science');
INSERT INTO Departments (abbreviation, name) VALUES('WGS','Women''s and Gender Studies');
INSERT INTO Departments (abbreviation, name) VALUES('WPS','Wood and Paper Science');
INSERT INTO Departments (abbreviation, name) VALUES('WRT','Professional Writing');
INSERT INTO Departments (abbreviation, name) VALUES('YFCS','Youth, Family, and Community Science');
INSERT INTO Departments (abbreviation, name) VALUES('ZO','Zoology');

INSERT INTO Nationality (country_name) VALUES('Afghanistan');
INSERT INTO Nationality (country_name) VALUES('Albania');
INSERT INTO Nationality (country_name) VALUES('Algeria');
INSERT INTO Nationality (country_name) VALUES('Andorra');
INSERT INTO Nationality (country_name) VALUES('Angola');
INSERT INTO Nationality (country_name) VALUES('Antigua and Barbuda');
INSERT INTO Nationality (country_name) VALUES('Argentina');
INSERT INTO Nationality (country_name) VALUES('Armenia');
INSERT INTO Nationality (country_name) VALUES('Australia');
INSERT INTO Nationality (country_name) VALUES('Austria');
INSERT INTO Nationality (country_name) VALUES('Azerbaijan');
INSERT INTO Nationality (country_name) VALUES('Bahamas');
INSERT INTO Nationality (country_name) VALUES('Bahrain');
INSERT INTO Nationality (country_name) VALUES('Bangladesh');
INSERT INTO Nationality (country_name) VALUES('Barbados');
INSERT INTO Nationality (country_name) VALUES('Belarus');
INSERT INTO Nationality (country_name) VALUES('Belgium');
INSERT INTO Nationality (country_name) VALUES('Belize');
INSERT INTO Nationality (country_name) VALUES('Benin');
INSERT INTO Nationality (country_name) VALUES('Bhutan');
INSERT INTO Nationality (country_name) VALUES('Bolivia');
INSERT INTO Nationality (country_name) VALUES('Bosnia and Herzegovina');
INSERT INTO Nationality (country_name) VALUES('Botswana');
INSERT INTO Nationality (country_name) VALUES('Brazil');
INSERT INTO Nationality (country_name) VALUES('Brunei');
INSERT INTO Nationality (country_name) VALUES('Bulgaria');
INSERT INTO Nationality (country_name) VALUES('Burkina Faso');
INSERT INTO Nationality (country_name) VALUES('Burundi');
INSERT INTO Nationality (country_name) VALUES('Cabo Verde');
INSERT INTO Nationality (country_name) VALUES('Cambodia');
INSERT INTO Nationality (country_name) VALUES('Cameroon');
INSERT INTO Nationality (country_name) VALUES('Canada');
INSERT INTO Nationality (country_name) VALUES('Central African Republic');
INSERT INTO Nationality (country_name) VALUES('Chad');
INSERT INTO Nationality (country_name) VALUES('Chile');
INSERT INTO Nationality (country_name) VALUES('China');
INSERT INTO Nationality (country_name) VALUES('Colombia');
INSERT INTO Nationality (country_name) VALUES('Comoros');
INSERT INTO Nationality (country_name) VALUES('Congo, Republic of the');
INSERT INTO Nationality (country_name) VALUES('Congo, Democratic Republic of the');
INSERT INTO Nationality (country_name) VALUES('Costa Rica');
INSERT INTO Nationality (country_name) VALUES('Cote d''Ivoire');
INSERT INTO Nationality (country_name) VALUES('Croatia');
INSERT INTO Nationality (country_name) VALUES('Cuba');
INSERT INTO Nationality (country_name) VALUES('Cyprus');
INSERT INTO Nationality (country_name) VALUES('Czech Republic');
INSERT INTO Nationality (country_name) VALUES('Denmark');
INSERT INTO Nationality (country_name) VALUES('Djibouti');
INSERT INTO Nationality (country_name) VALUES('Dominica');
INSERT INTO Nationality (country_name) VALUES('Dominican Republic');
INSERT INTO Nationality (country_name) VALUES('Ecuador');
INSERT INTO Nationality (country_name) VALUES('Egypt');
INSERT INTO Nationality (country_name) VALUES('El Salvador');
INSERT INTO Nationality (country_name) VALUES('Equatorial Guinea');
INSERT INTO Nationality (country_name) VALUES('Eritrea');
INSERT INTO Nationality (country_name) VALUES('Estonia');
INSERT INTO Nationality (country_name) VALUES('Ethiopia');
INSERT INTO Nationality (country_name) VALUES('Fiji');
INSERT INTO Nationality (country_name) VALUES('Finland');
INSERT INTO Nationality (country_name) VALUES('France');
INSERT INTO Nationality (country_name) VALUES('Gabon');
INSERT INTO Nationality (country_name) VALUES('Gambia');
INSERT INTO Nationality (country_name) VALUES('Georgia');
INSERT INTO Nationality (country_name) VALUES('Germany');
INSERT INTO Nationality (country_name) VALUES('Ghana');
INSERT INTO Nationality (country_name) VALUES('Greece');
INSERT INTO Nationality (country_name) VALUES('Grenada');
INSERT INTO Nationality (country_name) VALUES('Guatemala');
INSERT INTO Nationality (country_name) VALUES('Guinea');
INSERT INTO Nationality (country_name) VALUES('Guinea-Bissau');
INSERT INTO Nationality (country_name) VALUES('Guyana');
INSERT INTO Nationality (country_name) VALUES('Haiti');
INSERT INTO Nationality (country_name) VALUES('Honduras');
INSERT INTO Nationality (country_name) VALUES('Hungary');
INSERT INTO Nationality (country_name) VALUES('Iceland');
INSERT INTO Nationality (country_name) VALUES('India');
INSERT INTO Nationality (country_name) VALUES('Indonesia');
INSERT INTO Nationality (country_name) VALUES('Iran');
INSERT INTO Nationality (country_name) VALUES('Iraq');
INSERT INTO Nationality (country_name) VALUES('Ireland');
INSERT INTO Nationality (country_name) VALUES('Israel');
INSERT INTO Nationality (country_name) VALUES('Italy');
INSERT INTO Nationality (country_name) VALUES('Jamaica');
INSERT INTO Nationality (country_name) VALUES('Japan');
INSERT INTO Nationality (country_name) VALUES('Jordan');
INSERT INTO Nationality (country_name) VALUES('Kazakhstan');
INSERT INTO Nationality (country_name) VALUES('Kenya');
INSERT INTO Nationality (country_name) VALUES('Kiribati');
INSERT INTO Nationality (country_name) VALUES('Kosovo');
INSERT INTO Nationality (country_name) VALUES('Kuwait');
INSERT INTO Nationality (country_name) VALUES('Kyrgyzstan');
INSERT INTO Nationality (country_name) VALUES('Laos');
INSERT INTO Nationality (country_name) VALUES('Latvia');
INSERT INTO Nationality (country_name) VALUES('Lebanon');
INSERT INTO Nationality (country_name) VALUES('Lesotho');
INSERT INTO Nationality (country_name) VALUES('Liberia');
INSERT INTO Nationality (country_name) VALUES('Libya');
INSERT INTO Nationality (country_name) VALUES('Liechtenstein');
INSERT INTO Nationality (country_name) VALUES('Lithuania');
INSERT INTO Nationality (country_name) VALUES('Luxembourg');
INSERT INTO Nationality (country_name) VALUES('Macedonia');
INSERT INTO Nationality (country_name) VALUES('Madagascar');
INSERT INTO Nationality (country_name) VALUES('Malawi');
INSERT INTO Nationality (country_name) VALUES('Malaysia');
INSERT INTO Nationality (country_name) VALUES('Maldives');
INSERT INTO Nationality (country_name) VALUES('Mali');
INSERT INTO Nationality (country_name) VALUES('Malta');
INSERT INTO Nationality (country_name) VALUES('Marshall Islands');
INSERT INTO Nationality (country_name) VALUES('Mauritania');
INSERT INTO Nationality (country_name) VALUES('Mauritius');
INSERT INTO Nationality (country_name) VALUES('Mexico');
INSERT INTO Nationality (country_name) VALUES('Micronesia');
INSERT INTO Nationality (country_name) VALUES('Moldova');
INSERT INTO Nationality (country_name) VALUES('Monaco');
INSERT INTO Nationality (country_name) VALUES('Mongolia');
INSERT INTO Nationality (country_name) VALUES('Montenegro');
INSERT INTO Nationality (country_name) VALUES('Morocco');
INSERT INTO Nationality (country_name) VALUES('Mozambique');
INSERT INTO Nationality (country_name) VALUES('Myanmar (Burma)');
INSERT INTO Nationality (country_name) VALUES('Namibia');
INSERT INTO Nationality (country_name) VALUES('Nauru');
INSERT INTO Nationality (country_name) VALUES('Nepal');
INSERT INTO Nationality (country_name) VALUES('Netherlands');
INSERT INTO Nationality (country_name) VALUES('New Zealand');
INSERT INTO Nationality (country_name) VALUES('Nicaragua');
INSERT INTO Nationality (country_name) VALUES('Niger');
INSERT INTO Nationality (country_name) VALUES('Nigeria');
INSERT INTO Nationality (country_name) VALUES('North Korea');
INSERT INTO Nationality (country_name) VALUES('Norway');
INSERT INTO Nationality (country_name) VALUES('Oman');
INSERT INTO Nationality (country_name) VALUES('Pakistan');
INSERT INTO Nationality (country_name) VALUES('Palau');
INSERT INTO Nationality (country_name) VALUES('Palestine');
INSERT INTO Nationality (country_name) VALUES('Panama');
INSERT INTO Nationality (country_name) VALUES('Papua New Guinea');
INSERT INTO Nationality (country_name) VALUES('Paraguay');
INSERT INTO Nationality (country_name) VALUES('Peru');
INSERT INTO Nationality (country_name) VALUES('Philippines');
INSERT INTO Nationality (country_name) VALUES('Poland');
INSERT INTO Nationality (country_name) VALUES('Portugal');
INSERT INTO Nationality (country_name) VALUES('Qatar');
INSERT INTO Nationality (country_name) VALUES('Romania');
INSERT INTO Nationality (country_name) VALUES('Russia');
INSERT INTO Nationality (country_name) VALUES('Rwanda');
INSERT INTO Nationality (country_name) VALUES('St. Kitts and Nevis');
INSERT INTO Nationality (country_name) VALUES('St. Lucia');
INSERT INTO Nationality (country_name) VALUES('St. Vincent and The Grenadines');
INSERT INTO Nationality (country_name) VALUES('Samoa');
INSERT INTO Nationality (country_name) VALUES('San Marino');
INSERT INTO Nationality (country_name) VALUES('Sao Tome and Principe');
INSERT INTO Nationality (country_name) VALUES('Saudi Arabia');
INSERT INTO Nationality (country_name) VALUES('Senegal');
INSERT INTO Nationality (country_name) VALUES('Serbia');
INSERT INTO Nationality (country_name) VALUES('Seychelles');
INSERT INTO Nationality (country_name) VALUES('Sierra Leone');
INSERT INTO Nationality (country_name) VALUES('Singapore');
INSERT INTO Nationality (country_name) VALUES('Slovakia');
INSERT INTO Nationality (country_name) VALUES('Slovenia');
INSERT INTO Nationality (country_name) VALUES('Solomon Islands');
INSERT INTO Nationality (country_name) VALUES('Somalia');
INSERT INTO Nationality (country_name) VALUES('South Africa');
INSERT INTO Nationality (country_name) VALUES('South Korea');
INSERT INTO Nationality (country_name) VALUES('South Sudan');
INSERT INTO Nationality (country_name) VALUES('Spain');
INSERT INTO Nationality (country_name) VALUES('Sri Lanka');
INSERT INTO Nationality (country_name) VALUES('Sudan');
INSERT INTO Nationality (country_name) VALUES('Suriname');
INSERT INTO Nationality (country_name) VALUES('Swaziland');
INSERT INTO Nationality (country_name) VALUES('Sweden');
INSERT INTO Nationality (country_name) VALUES('Switzerland');
INSERT INTO Nationality (country_name) VALUES('Syria');
INSERT INTO Nationality (country_name) VALUES('Taiwan');
INSERT INTO Nationality (country_name) VALUES('Tajikistan');
INSERT INTO Nationality (country_name) VALUES('Tanzania');
INSERT INTO Nationality (country_name) VALUES('Thailand');
INSERT INTO Nationality (country_name) VALUES('Timor-Leste');
INSERT INTO Nationality (country_name) VALUES('Togo');
INSERT INTO Nationality (country_name) VALUES('Tonga');
INSERT INTO Nationality (country_name) VALUES('Trinidad and Tobago');
INSERT INTO Nationality (country_name) VALUES('Tunisia');
INSERT INTO Nationality (country_name) VALUES('Turkey');
INSERT INTO Nationality (country_name) VALUES('Turkmenistan');
INSERT INTO Nationality (country_name) VALUES('Tuvalu');
INSERT INTO Nationality (country_name) VALUES('Uganda');
INSERT INTO Nationality (country_name) VALUES('Ukraine');
INSERT INTO Nationality (country_name) VALUES('United Arab Emirates');
INSERT INTO Nationality (country_name) VALUES('UK (United Kingdom)');
INSERT INTO Nationality (country_name) VALUES('USA (United States of America)');
INSERT INTO Nationality (country_name) VALUES('Uruguay');
INSERT INTO Nationality (country_name) VALUES('Uzbekistan');
INSERT INTO Nationality (country_name) VALUES('Vanuatu');
INSERT INTO Nationality (country_name) VALUES('Vatican City (Holy See)');
INSERT INTO Nationality (country_name) VALUES('Venezuela');
INSERT INTO Nationality (country_name) VALUES('Vietnam');
INSERT INTO Nationality (country_name) VALUES('Yemen');
INSERT INTO Nationality (country_name) VALUES('Zambia');
INSERT INTO Nationality (country_name) VALUES('Zimbabwe');

INSERT INTO Degree_Program (program) VALUES('B.S.');
INSERT INTO Degree_Program (program) VALUES('M.S.');
INSERT INTO Degree_Program (program) VALUES('M.A.');
INSERT INTO Degree_Program (program) VALUES('Ph.D.');

INSERT INTO Faculty_Category (category) VALUES('Assistant Professor');
INSERT INTO Faculty_Category (category) VALUES('Associate Professor');
INSERT INTO Faculty_Category (category) VALUES('Professor');
INSERT INTO Faculty_Category (category) VALUES('Lecturer');

CREATE or replace FUNCTION insert_student (fname in varchar2,lname in varchar2,id in number,
  status in varchar2,country_name in varchar2,phone in varchar2,
  alt_phone in varchar2, dob in date, sex in varchar2,street in varchar2,city in varchar2,
  postcode in varchar2,program in varchar2,year in number) return integer 
  is
  pragma autonomous_transaction;
  begin
  
  insert into patron values (fname,lname,id,status,country_name);
  commit;
  insert into student values (phone,alt_phone,dob,sex,street,city,postcode,id,program,year);
  commit;
  
  return 1;
  end;
  
  
CREATE or replace FUNCTION insert_faculty (fname in varchar2,lname in varchar2,id in number,
  status in varchar2,country_name in varchar2,category in varchar2) return integer 
  is
  
  pragma autonomous_transaction;
  begin
  
  insert into patron values (fname,lname,id,status,country_name);
  commit;
  insert into faculty values (category,id);
  commit;
  
  return 1;
  end;
  
  select INSERT_FACULTY('Rob','St Amant',0001,'GOOD','USA (United States of America)','Professor') from dual;
  select INSERT_FACULTY('Robert','Baratheon',0002,'GOOD','India','Professor') from dual;
  select INSERT_FACULTY('Ash','Katchem',0003,'GOOD','USA (United States of America)','Professor') from dual;
  select INSERT_FACULTY('Matteo','Darmian',0004,'GOOD','Italy','Assistant Professor') from dual;
  select INSERT_FACULTY('Cristiano','Naldo',0005,'GOOD','Portugal','Lecturer') from dual;
  
    select INSERT_STUDENT('Maria','Shara',10,'GOOD','Russia','929786773','8900020020','12-Jun-1993','Female',
    '23-Wilson Road','Raleigh',27606,'M.S.',1) from dual;
      select INSERT_STUDENT('Roger','Fedex',12,'GOOD','Serbia','929996773','8909020022','12-May-1993','Male',
    '15-Basel ROad','Basel',22606,'M.A.',2) from dual;
      select INSERT_STUDENT('Sania','Mir',13,'GOOD','India','9999333','8900020','12-OCT-1992','Female',
    '19-Yawn Road','Raleigh',27606,'M.S.',2) from dual;
      select INSERT_STUDENT('Ton','Hewitt',14,'GOOD','Australia','929786773','8901020020','12-Jun-1993','Male',
    '45-Snorlax Road','Raleigh',27606,'B.S.',1) from dual;
      select INSERT_STUDENT('Rafa','Nadal',15,'GOOD','Spain','829746773','9944020020','12-Jan-1988','Male',
    '25-Estona Road','Madrid',25606,'M.S.',1) from dual;


